# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color:rgb(101, 40, 247);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.squareFrame = QtWidgets.QFrame(self.centralwidget)
        self.squareFrame.setGeometry(QtCore.QRect(190, 110, 120, 80))
        self.squareFrame.setStyleSheet("background-color:rgb(250, 50, 83);\n"
"")
        self.squareFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.squareFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.squareFrame.setObjectName("squareFrame")
        self.circleFrame = QtWidgets.QFrame(self.centralwidget)
        self.circleFrame.setGeometry(QtCore.QRect(190, 230, 120, 80))
        self.circleFrame.setStyleSheet("background-color:rgb(36, 179, 83)\n"
"")
        self.circleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.circleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circleFrame.setObjectName("circleFrame")
        self.triangleFrame = QtWidgets.QFrame(self.centralwidget)
        self.triangleFrame.setGeometry(QtCore.QRect(190, 350, 120, 80))
        self.triangleFrame.setStyleSheet("background-color:rgb(42, 125, 209)\n"
"")
        self.triangleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.triangleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.triangleFrame.setObjectName("triangleFrame")
        self.starFrame = QtWidgets.QFrame(self.centralwidget)
        self.starFrame.setGeometry(QtCore.QRect(190, 470, 120, 80))
        self.starFrame.setStyleSheet("background-color:rgb(115, 51, 128)")
        self.starFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.starFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.starFrame.setObjectName("starFrame")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 80, 71, 21))
        self.label.setStyleSheet("font: italic 16pt \"Ubuntu\";\n"
"color:white;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 200, 66, 17))
        self.label_2.setStyleSheet("font: italic 16pt \"Ubuntu\";\n"
"color:white;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 310, 81, 31))
        self.label_3.setStyleSheet("font: italic 16pt \"Ubuntu\";\n"
"color:white;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(230, 440, 66, 17))
        self.label_4.setStyleSheet("font: italic 16pt \"Ubuntu\";\n"
"color:white;")
        self.label_4.setObjectName("label_4")
        self.squareBtn = QtWidgets.QPushButton(self.centralwidget)
        self.squareBtn.setGeometry(QtCore.QRect(390, 110, 191, 71))
        self.squareBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.squareBtn.setStyleSheet("QPushButton {\n"
"font: 18pt \"Bahnschrift Condensed\";\n"
"background-color:rgb(80, 64, 153);\n"
"color:white;\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(160, 118, 249);\n"
"}\n"
"")
        self.squareBtn.setObjectName("squareBtn")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 10, 511, 61))
        self.label_5.setStyleSheet("font: 75 24pt \"Bahnschrift\";\n"
"color:white;")
        self.label_5.setObjectName("label_5")
        self.circleBtn = QtWidgets.QPushButton(self.centralwidget)
        self.circleBtn.setGeometry(QtCore.QRect(390, 230, 191, 71))
        self.circleBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.circleBtn.setStyleSheet("QPushButton {\n"
"font: 18pt \"Bahnschrift Condensed\";\n"
"background-color:rgb(80, 64, 153);\n"
"color:white;\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(160, 118, 249);\n"
"}\n"
"")
        self.circleBtn.setObjectName("circleBtn")
        self.triangleBtn = QtWidgets.QPushButton(self.centralwidget)
        self.triangleBtn.setGeometry(QtCore.QRect(390, 350, 191, 71))
        self.triangleBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.triangleBtn.setStyleSheet("QPushButton {\n"
"font: 18pt \"Bahnschrift Condensed\";\n"
"background-color:rgb(80, 64, 153);\n"
"color:white;\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(160, 118, 249);\n"
"}\n"
"")
        self.triangleBtn.setObjectName("triangleBtn")
        self.starBtn = QtWidgets.QPushButton(self.centralwidget)
        self.starBtn.setGeometry(QtCore.QRect(390, 470, 191, 71))
        self.starBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.starBtn.setStyleSheet("QPushButton {\n"
"font: 18pt \"Bahnschrift Condensed\";\n"
"background-color:rgb(80, 64, 153);\n"
"color:white;\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(160, 118, 249);\n"
"}\n"
"")
        self.starBtn.setObjectName("starBtn")
        self.okBtn = QtWidgets.QPushButton(self.centralwidget)
        self.okBtn.setGeometry(QtCore.QRect(680, 540, 101, 41))
        self.okBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.okBtn.setStyleSheet("QPushButton {\n"
"font: 18pt \"Bahnschrift Condensed\";\n"
"background-color:rgb(80, 64, 153);\n"
"color:white;\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(160, 118, 249);\n"
"}\n"
"")
        self.okBtn.setObjectName("okBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.okBtn.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Square"))
        self.label_2.setText(_translate("MainWindow", "Circle"))
        self.label_3.setText(_translate("MainWindow", "Triangle"))
        self.label_4.setText(_translate("MainWindow", "Star"))
        self.squareBtn.setText(_translate("MainWindow", "Change color"))
        self.label_5.setText(_translate("MainWindow", "SETTING COLORS FOR SHAPES"))
        self.circleBtn.setText(_translate("MainWindow", "Change color"))
        self.triangleBtn.setText(_translate("MainWindow", "Change color"))
        self.starBtn.setText(_translate("MainWindow", "Change color"))
        self.okBtn.setText(_translate("MainWindow", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
