# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PIL import ImageColor

with open('colors.txt', 'r') as f:
    colors = f.readlines()
square = colors[0].replace('(','').replace(')','').split()
circle = colors[1].replace('(','').replace(')','').split()
triangle = colors[2].replace('(','').replace(')','').split()
star = colors[3].replace('(','').replace(')','').split()



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(190, 110, 120, 80))
        self.frame.setStyleSheet("background-color:rgb(250, 50, 83);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(190, 230, 120, 80))
        self.frame_2.setStyleSheet("background-color:rgb(36, 179, 83)\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(190, 350, 120, 80))
        self.frame_3.setStyleSheet("background-color:rgb(42, 125, 209)\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(190, 470, 120, 80))
        self.frame_4.setStyleSheet("background-color:rgb(115, 51, 128)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 80, 66, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 200, 66, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 320, 66, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 440, 66, 17))
        self.label_4.setObjectName("label_4")
        self.squareBtn = QtWidgets.QPushButton(self.centralwidget)
        self.squareBtn.setGeometry(QtCore.QRect(470, 120, 111, 25))
        self.squareBtn.setObjectName("squareBtn")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(310, 20, 341, 17))
        self.label_5.setObjectName("label_5")
        self.circleBtn = QtWidgets.QPushButton(self.centralwidget)
        self.circleBtn.setGeometry(QtCore.QRect(470, 260, 111, 25))
        self.circleBtn.setObjectName("circleBtn")
        self.triangleBtn = QtWidgets.QPushButton(self.centralwidget)
        self.triangleBtn.setGeometry(QtCore.QRect(470, 380, 111, 25))
        self.triangleBtn.setObjectName("triangleBtn")
        self.starBtn = QtWidgets.QPushButton(self.centralwidget)
        self.starBtn.setGeometry(QtCore.QRect(470, 510, 111, 25))
        self.starBtn.setObjectName("starBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.squareBtn.clicked.connect(self.colorpicker_square)
        self.circleBtn.clicked.connect(self.colorpicker_circle)
        self.triangleBtn.clicked.connect(self.colorpicker_triangle)
        self.starBtn.clicked.connect(self.colorpicker_star)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def colorpicker_square(self):
        col = QColorDialog.getColor()
        if col.isValid():
            rgb_square = ImageColor.getcolor(col.name(), "RGB")
            colors[0] = str(rgb_square) + '\n'
            with open('colors.txt', 'w') as f:
                f.writelines(colors)
            self.frame.setStyleSheet("background-color: %s;\n" % col.name())
    def colorpicker_circle(self):
        col = QColorDialog.getColor()
        if col.isValid():
            rgb_circle = ImageColor.getcolor(col.name(), "RGB")
            colors[1] = str(rgb_circle) + '\n'
            with open('colors.txt', 'w') as f:
                f.writelines(colors)
            self.frame_2.setStyleSheet("background-color: %s;\n" % col.name())
    def colorpicker_triangle(self):
        col = QColorDialog.getColor()
        if col.isValid():
            rgb_triangle = ImageColor.getcolor(col.name(), "RGB")
            colors[2] = str(rgb_triangle) + '\n'
            with open('colors.txt', 'w') as f:
                f.writelines(colors)
            self.frame_3.setStyleSheet("background-color: %s;\n" % col.name())
    def colorpicker_star(self):
        col = QColorDialog.getColor()
        if col.isValid():
            rgb_star = ImageColor.getcolor(col.name(), "RGB")
            colors[3] = str(rgb_star) + '\n'
            with open('colors.txt', 'w') as f:
                f.writelines(colors)
            self.frame_4.setStyleSheet("background-color: %s;\n" % col.name())


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Square"))
        self.label_2.setText(_translate("MainWindow", "Circle"))
        self.label_3.setText(_translate("MainWindow", "Triangle"))
        self.label_4.setText(_translate("MainWindow", "Star"))
        self.squareBtn.setText(_translate("MainWindow", "Change color"))
        self.label_5.setText(_translate("MainWindow", "SETTING COLORS FOR SHAPES"))
        self.circleBtn.setText(_translate("MainWindow", "Change color"))
        self.triangleBtn.setText(_translate("MainWindow", "Change color"))
        self.starBtn.setText(_translate("MainWindow", "Change color"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

