# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startUI_updated.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import cv2
from PyQt5 import QtCore
import numpy as np
from PyQt5.QtCore import *
from PyQt5.QtGui import QImage, QPixmap
from PyQt5.QtWidgets import QDialog, QApplication, QWidget
from PyQt5.uic import loadUi
import cv2
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import time
import onnxruntime as ort

frame_shape = (640, 480)
target_shape = (256, 256, 3)
half_width = target_shape[0] // 2
half_height = target_shape[1] // 2
x0 = frame_shape[0] // 2 - half_width
y0 = frame_shape[1] // 2 - half_height
x1 = frame_shape[0] // 2 + half_width
y1 = frame_shape[1] // 2 + half_height

background = -1
ort_session = ort.InferenceSession('model.onnx')
input_name = ort_session.get_inputs()[0].name
output_name = ort_session.get_outputs()[0].name
def create_img(mask_output):
    r = np.zeros((256, 256), dtype=np.uint8)
    g = np.zeros((256, 256), dtype=np.uint8)
    b = np.zeros((256, 256), dtype=np.uint8)
    r[mask_output == 1] = 250
    r[mask_output == 2] = 36
    r[mask_output == 3] = 42
    r[mask_output == 4] = 115

    g[mask_output == 1] = 50
    g[mask_output == 2] = 179
    g[mask_output == 3] = 125
    g[mask_output == 4] = 51

    b[mask_output == 1] = 83
    b[mask_output == 2] = 83
    b[mask_output == 3] = 209
    b[mask_output == 4] = 128

    output = np.stack([b, g, r], axis=-1)
    return output
def create_img_bg(roi, mask_output):
    b, g, r = cv2.split(roi)
    r[mask_output == 1] = 250
    r[mask_output == 2] = 36
    r[mask_output == 3] = 42
    r[mask_output == 4] = 115

    g[mask_output == 1] = 50
    g[mask_output == 2] = 179
    g[mask_output == 3] = 125
    g[mask_output == 4] = 51

    b[mask_output == 1] = 83
    b[mask_output == 2] = 83
    b[mask_output == 3] = 209
    b[mask_output == 4] = 128

    output = np.stack([b, g, r], axis=-1)
    return output
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(899, 669)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(800, 600, 88, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(690, 600, 88, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 811, 481))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(3)
        self.label.setMidLineWidth(3)
        self.label.setObjectName("label")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 899, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.camera = Camera()
        self.camera.image.connect(self.update_image)
        self.camera.start()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def update_image(self, frame):
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        image = QImage(frame, frame.shape[1], frame.shape[0], QImage.Format_RGB888)
        self.label.setPixmap(QPixmap.fromImage(image))
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Back"))
        self.pushButton_2.setText(_translate("MainWindow", "Connect"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
class Camera(QThread):
    image = pyqtSignal(np.ndarray)
    def __init__(self):
        super().__init__()
        self.flag = True
    def run(self):
        background = -1
        prev_time = 0 
        new_time = 0
        self.capture = cv2.VideoCapture(0)
        while self.flag:
            ret, frame = self.capture.read()
            sample_window = frame[y0:y0+target_shape[1], x0:x0+target_shape[0]].copy()
            
            input_to_model = cv2.cvtColor(sample_window, cv2.COLOR_BGR2RGB)
            input_to_model = input_to_model.astype(np.float32) / 255.0
            input_to_model = np.expand_dims(input_to_model, axis=0)
            y_pred = ort_session.run([output_name], {input_name: input_to_model})
            res = np.argmax(y_pred[0][0], axis=-1)
            mask_output = create_img(res)
            cv2.rectangle(frame, (x0, y0), (x1, y1), (0, 255, 0), 2)
            if background == -1:
                cv2.putText(frame, 'Black mode', (10, 60), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 1)
                
            else:
                cv2.putText(frame, 'Background mode', (10, 60), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 1)
                mask_output = create_img_bg(sample_window, res)
            frame[y0:y0+target_shape[1], x0:x0+target_shape[0]] = mask_output
            frame = cv2.flip(frame, 1)
            new_time = time.time()
            fps = str(int(1 / (new_time - prev_time)))
            cv2.putText(frame, str(int(fps)), (5, 30), cv2.FONT_HERSHEY_PLAIN, 2, (0, 255, 0), 1)
            prev_time = new_time
            k = cv2.waitKey(1)
            self.image.emit(frame)
            if k == ord('b'):
                background = -background
    def stop(self):
        self.flag = False
        self.wait()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
