# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from startUI import Ui_StartWindow 
from settingUI import Ui_SettingWindow


class Ui_MainWindow(QMainWindow):
    
    def __init__(self):
     
        super().__init__()
        self.setupUi()
    def closeEvent(self, event):
        print('closed')

        
    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(689, 543)
        self.setStyleSheet("background-color:rgb(101, 40, 247);")
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 80, 531, 151))

        self.label.setStyleSheet("font: 75 24pt \"Bahnschrift\";\n"
"color:white;")
        self.label.setObjectName("label")
        self.settingBtn = QtWidgets.QPushButton(self.centralwidget)
        self.settingBtn.setGeometry(QtCore.QRect(260, 330, 181, 71))
        self.settingBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.settingBtn.setStyleSheet("QPushButton {\n"
"font: 18pt \"Bahnschrift Condensed\";\n"
"background-color:rgb(80, 64, 153);\n"
"color:white;\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(160, 118, 249);\n"
"}\n"
"")
        self.settingBtn.setObjectName("settingBtn")
        
        self.startBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startBtn.setGeometry(QtCore.QRect(260, 250, 181, 71))
        self.startBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.startBtn.setStyleSheet("QPushButton {\n"
"font: 18pt \"Bahnschrift Condensed\";\n"
"background-color:rgb(80, 64, 153);\n"
"color:white;\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(160, 118, 249);\n"
"}\n"
"")
        self.startBtn.setObjectName("startBtn")
        
        self.quitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.quitBtn.setGeometry(QtCore.QRect(260, 410, 181, 71))
        self.quitBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.quitBtn.setStyleSheet("QPushButton {\n"
"font: 18pt \"Bahnschrift Condensed\";\n"
"background-color:rgb(80, 64, 153);\n"
"color:white;\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(160, 118, 249);\n"
"}\n"
"")
        self.quitBtn.setObjectName("quitBtn")
        self.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar()
        self.statusbar.setObjectName("statusbar")
        self.setStatusBar(self.statusbar)

        self.retranslateUi()
        self.quitBtn.clicked.connect(self.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(self)
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Shape Segmentation"))
        self.label.setText(_translate("MainWindow", "SHAPE SEGMENTATION"))
        self.settingBtn.setText(_translate("MainWindow", "Setting"))
        self.startBtn.setText(_translate("MainWindow", "Start"))
        self.quitBtn.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    
    ui = Ui_MainWindow()
    ui.setupUi()
    ui.show()
    sys.exit(app.exec_())
