# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(689, 543)
        MainWindow.setStyleSheet("background-color:rgb(101, 40, 247);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 80, 531, 151))
        self.label.setStyleSheet("font: 75 24pt \"Bahnschrift\";\n"
"color:white;\n"
"text-shadow: 2px 2px;")
        self.label.setObjectName("label")
        self.settingBtn = QtWidgets.QPushButton(self.centralwidget)
        self.settingBtn.setGeometry(QtCore.QRect(260, 330, 181, 71))
        self.settingBtn.setStyleSheet("QPushButton {\n"
"font: 18pt \"Bahnschrift Condensed\";\n"
"background-color:rgb(80, 64, 153);\n"
"color:white;\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(160, 118, 249);\n"
"}\n"
"")
        self.settingBtn.setObjectName("settingBtn")
        self.startBtn = QtWidgets.QPushButton(self.centralwidget)
        self.startBtn.setGeometry(QtCore.QRect(260, 250, 181, 71))
        self.startBtn.setStyleSheet("QPushButton {\n"
"font: 18pt \"Bahnschrift Condensed\";\n"
"background-color:rgb(80, 64, 153);\n"
"color:white;\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(160, 118, 249);\n"
"}\n"
"")
        self.startBtn.setObjectName("startBtn")
        self.quitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.quitBtn.setGeometry(QtCore.QRect(260, 410, 181, 71))
        self.quitBtn.setStyleSheet("QPushButton {\n"
"font: 18pt \"Bahnschrift Condensed\";\n"
"background-color:rgb(80, 64, 153);\n"
"color:white;\n"
"border-radius:12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgb(160, 118, 249);\n"
"}\n"
"")
        self.quitBtn.setObjectName("quitBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 689, 26))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.quitBtn.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "SHAPE SEGMENTATION"))
        self.settingBtn.setText(_translate("MainWindow", "Setting"))
        self.startBtn.setText(_translate("MainWindow", "Start"))
        self.quitBtn.setText(_translate("MainWindow", "Quit"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
